### ISSUE TITLE
Syntax error on rules

### ISSUE THREAD

**Issue by Manu1400** [mboveiri/ublock-iran#1]
Syntax error on : 
- `http://engine.adfinder.io/pro.ashx`
- #L6 `||www.soft98.ir$script,first-party` (error: Unknown filter option)
- `||www.farsroid.com/file$first-party` (error: Unknown filter option)
- `||www.farsmovie.ir$script,first-party` (error: Unknown filter option)
- `||www.farsmovie.ir$inline-script,first-party` (error: Unknown filter option)
- `||www.android30t.com/wp-content/themes/android30t/files$script,first-party` (error: Unknown filter option)
- `||www.campec.ir$inline-script,first-party` (error: Unknown filter option)

On console: 
> Error in event handler for (unknown): SyntaxError: Failed to execute 'addRule' on 'CSSStyleSheet': Failed to parse the rule (...)

Note: Tested with _AdBlock Plus_ on Google Chrome browser.

**Comment by Manu1400** [comment]
Is not a valid CSS selector: 
- `'a[href^*="http://computerir.com"]'`
- `'a[href^*="http://www.01kala.com/"]'`
- `'a[href^*="http://tidbit.ir"]'`
- `'a[href^*="http://www.sonyir.com"]'`
- `'a[href^*="http://www.kishonline.com/"]'`

**Comment by mboveiri** [comment]
Hi @Manu1400 

Thanks for the report, i think it's happens cause the differences between "Rules Writing" in "uBlock" and "AdBlock+" and i preferred uBlock for my List.
However i edited the filter list and i think bugs are fixed, i checking this ASAP.
Thanks.

**Comment by Manu1400** [comment]
Fixed. Don't have the error in console, after refresh (download) the filter list.
