### ISSUE TITLE
soft98 issue

### ISSUE THREAD

**Issue by drupalshift** [mboveiri/ublock-iran#2]
وقتی به صفحات دانلود سافت ۹۸ میرم 
باکسی که باید لینک های دانلود رو نمایش بده این پیام رو میده

![chrome-capture (2)](https://user-images.githubusercontent.com/9895625/58748756-332a1b80-8492-11e9-9a22-22e1b7f46dca.jpg)

وقتی غیرفعال باشه ublock درست میشه

**Comment by mboveiri** [comment]
با سلام و وقت بخیر.
متاسفانه مدیر این سایت که یک سایت پایرسی (دانلود غیر قانونی) در ایران هست ، یک بازی موش و گربه راه انداختن و به محض به روز رسانی فیلتر لیست ، با تغییر در طراحی سایت ، بلاکر رو بی اثر میکنن ، متاسفانه راه حل دائمی برای این سایت وجود نداره ولی شما می تونید موقتن با قرار دادن کد زیر در قسمت

` My Filters `

افزونه به صورت موقت مشکل را برطرف کنید.

> کد : 
> 
> `soft98.ir##div[class*="dp-c"]:style(display: block !important)
> `
>

**Comment by mboveiri** [comment]
فعلا به صورت موقت با به روزرسانی مستمر لیست مشکل مرتفع شده، ممنون از تلاش همه ی دوستان که برای حذف تبلیغات از این سایت کمک می کنند.
قبل از رفتن به این سایت حتماً فیلتر لیست را از قسمت Filter lists با زدن روی 🕒 کنار فیلتر لیست سپس دکمه Update به روز رسانی کنید.

**Comment by F50Ci37Y** [comment]
@mboveiri 
سلام هنوز مشکل پابرجاست
اگر تند تند مدیر سایت عوض میکنه اسم کلاس هارو کلا نذاریدش توی لیست
[عکس](http://uplod.ir/btx14luzcmoj/Screenshot_from_2019-11-10_02-20-49.png.htm
)
[عکس](http://uplod.ir/prl0j6u95lpz/Screenshot_from_2019-11-10_02-20-58.png.htm
)
